// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsDg-G6gOFqnLpZ0fnNkAbOSopyrR0niA',
    appId: '1:163395459823:web:4d09faefc9b107e0d0591a',
    messagingSenderId: '163395459823',
    projectId: 'appauth-ee8a5',
    authDomain: 'appauth-ee8a5.firebaseapp.com',
    storageBucket: 'appauth-ee8a5.firebasestorage.app',
    measurementId: 'G-ECQ87C23QX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdkAMbnmAcPgBSDarA1utXQGPa3h9be40',
    appId: '1:163395459823:android:3391a83442e6b097d0591a',
    messagingSenderId: '163395459823',
    projectId: 'appauth-ee8a5',
    storageBucket: 'appauth-ee8a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqlr-Ckp4PdnG9_FpvyS1f85V-qEUGFu0',
    appId: '1:163395459823:ios:f0862cba81bd10abd0591a',
    messagingSenderId: '163395459823',
    projectId: 'appauth-ee8a5',
    storageBucket: 'appauth-ee8a5.firebasestorage.app',
    androidClientId: '163395459823-34rahf13ifgq1th0g22k16p7ftba9a7c.apps.googleusercontent.com',
    iosClientId: '163395459823-qpkt93h1koousv86hosngvihmsmpmrh8.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqlr-Ckp4PdnG9_FpvyS1f85V-qEUGFu0',
    appId: '1:163395459823:ios:f0862cba81bd10abd0591a',
    messagingSenderId: '163395459823',
    projectId: 'appauth-ee8a5',
    storageBucket: 'appauth-ee8a5.firebasestorage.app',
    androidClientId: '163395459823-34rahf13ifgq1th0g22k16p7ftba9a7c.apps.googleusercontent.com',
    iosClientId: '163395459823-qpkt93h1koousv86hosngvihmsmpmrh8.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsDg-G6gOFqnLpZ0fnNkAbOSopyrR0niA',
    appId: '1:163395459823:web:96495da453365cfdd0591a',
    messagingSenderId: '163395459823',
    projectId: 'appauth-ee8a5',
    authDomain: 'appauth-ee8a5.firebaseapp.com',
    storageBucket: 'appauth-ee8a5.firebasestorage.app',
    measurementId: 'G-7MNEQBRN8J',
  );
}
