// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx2gZaW13i_tsymRiQwUCWlCQnWSjleCs',
    appId: '1:473658524092:web:1fd8343ff19abe6f87abb9',
    messagingSenderId: '473658524092',
    projectId: 'mini-project-4ec21',
    authDomain: 'mini-project-4ec21.firebaseapp.com',
    storageBucket: 'mini-project-4ec21.firebasestorage.app',
    measurementId: 'G-SBRP47QXCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6AxC263xj3snZ027HMsr4scarT7A9kcA',
    appId: '1:473658524092:android:247c5ebf2852c3e787abb9',
    messagingSenderId: '473658524092',
    projectId: 'mini-project-4ec21',
    storageBucket: 'mini-project-4ec21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf6QYE9X6Q6hHX7XYXjAbsSiSPqb56us8',
    appId: '1:473658524092:ios:14eaae0b4cbbaed187abb9',
    messagingSenderId: '473658524092',
    projectId: 'mini-project-4ec21',
    storageBucket: 'mini-project-4ec21.firebasestorage.app',
    androidClientId: '473658524092-kp0qnkf9rrdt3sg6et9ok3apmg6mkr35.apps.googleusercontent.com',
    iosClientId: '473658524092-5scng6qj48rcu1836k2lcc1n4auemsug.apps.googleusercontent.com',
    iosBundleId: 'com.example.yogaAppClean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf6QYE9X6Q6hHX7XYXjAbsSiSPqb56us8',
    appId: '1:473658524092:ios:14eaae0b4cbbaed187abb9',
    messagingSenderId: '473658524092',
    projectId: 'mini-project-4ec21',
    storageBucket: 'mini-project-4ec21.firebasestorage.app',
    androidClientId: '473658524092-kp0qnkf9rrdt3sg6et9ok3apmg6mkr35.apps.googleusercontent.com',
    iosClientId: '473658524092-5scng6qj48rcu1836k2lcc1n4auemsug.apps.googleusercontent.com',
    iosBundleId: 'com.example.yogaAppClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx2gZaW13i_tsymRiQwUCWlCQnWSjleCs',
    appId: '1:473658524092:web:5f726bf8c5f90b4387abb9',
    messagingSenderId: '473658524092',
    projectId: 'mini-project-4ec21',
    authDomain: 'mini-project-4ec21.firebaseapp.com',
    storageBucket: 'mini-project-4ec21.firebasestorage.app',
    measurementId: 'G-Y3BBNVH2NM',
  );
}
