// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbnZCD8l6ytBuDmNdhNKU2LfV7fcIJLzE',
    appId: '1:597418904741:web:b56bd9c3628253441b514c',
    messagingSenderId: '597418904741',
    projectId: 'calculatorfirebase-181ca',
    authDomain: 'calculatorfirebase-181ca.firebaseapp.com',
    storageBucket: 'calculatorfirebase-181ca.firebasestorage.app',
    measurementId: 'G-S8ZNSV8ZEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAheY5-g058obvR8yevrhZDbTdA5nBFYTQ',
    appId: '1:597418904741:android:a716f025022dfbcb1b514c',
    messagingSenderId: '597418904741',
    projectId: 'calculatorfirebase-181ca',
    storageBucket: 'calculatorfirebase-181ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ0a_YjRnisH0mz8ohfHLIU3kBsO9l8kI',
    appId: '1:597418904741:ios:de9d4890245591181b514c',
    messagingSenderId: '597418904741',
    projectId: 'calculatorfirebase-181ca',
    storageBucket: 'calculatorfirebase-181ca.firebasestorage.app',
    iosBundleId: 'com.example.calculatorfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ0a_YjRnisH0mz8ohfHLIU3kBsO9l8kI',
    appId: '1:597418904741:ios:de9d4890245591181b514c',
    messagingSenderId: '597418904741',
    projectId: 'calculatorfirebase-181ca',
    storageBucket: 'calculatorfirebase-181ca.firebasestorage.app',
    iosBundleId: 'com.example.calculatorfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbnZCD8l6ytBuDmNdhNKU2LfV7fcIJLzE',
    appId: '1:597418904741:web:8dcf373a69b643201b514c',
    messagingSenderId: '597418904741',
    projectId: 'calculatorfirebase-181ca',
    authDomain: 'calculatorfirebase-181ca.firebaseapp.com',
    storageBucket: 'calculatorfirebase-181ca.firebasestorage.app',
    measurementId: 'G-CXW7DRQN5V',
  );
}
